export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const USER_LOADING = "USER_LOADING";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const IS_ADMIN = "IS_ADMIN";
export const IS_NOT_ADMIN = "IS_NOT_ADMIN";

export const GET_CURRENT_TOURNAMENTS = "GET_CURRENT_TOURNAMENTS";
export const GET_MY_CURRENT_TOURNAMENTS = "GET_MY_CURRENT_TOURNAMENTS";
export const MY_TOURNAMENTS_LOADING = "MY_TOURNAMENTS_LOADING";

export const TOURNAMENTS_LOADING = "TOURNAMENTS_LOADING";

export const TOURNAMENTS_ADMIN_LOADING = "TOURNAMENTS_ADMIN_LOADING";
export const TOURNAMENT_ADMIN_LOADING = "TOURNAMENT_ADMIN_LOADING";
export const GET_CURRENT_ADMIN_TOURNAMENTS = "GET_CURRENT_ADMIN_TOURNAMENTS";
export const GET_CURRENT_ADMIN_TOURNAMENT = "GET_CURRENT_ADMIN_TOURNAMENT";
export const GET_ADMIN_TOURNAMENT_ROUNDS = "GET_ADMIN_TOURNAMENT_ROUNDS";
export const ROUNDS_LOADING = "ROUNDS_LOADING";

export const SET_SELECTED_TOURNAMENT = "SET_SELECTED_TOURNAMENT";
export const APUNTARSE_LOADING = "APUNTARSE_LOADING";
export const SET_SELECTED_TOURNAMENT_INFO = "SET_SELECTED_TOURNAMENT_INFO";
export const SET_TORNEO_NC_INFO = "SET_TORNEO_NC_INFO";

export const REGISTRO_ADMIN_LOADING = "REGISTRO_ADMIN_LOADING";
export const SET_SELECTED_ADMIN_TOURNAMENT = "SET_SELECTED_ADMIN_TOURNAMENT";

export const GET_USER1 = "GET_USER1";
export const GET_USER2 = "GET_USER2";

export const GET_MI_RONDA_INFO = "GET_MI_RONDA_INFO";
export const RONDA_INFO_NULL = "RONDA_INFO_NULL";
export const RONDA_LOADING = "RONDA_LOADING";
export const TORNEO_COMENZADO_LOADING = "TORNEO_COMENZADO_LOADING";
export const TORNEO_NO_COMENZADO_LOADING = "TORNEO_NO_COMENZADO_LOADING";
export const PREVIOUS_ROUNDS_LOADING = "PREVIOUS_ROUNDS_LOADING";
export const GET_PREVIOUS_ROUND = "GET_PREVIOUS_ROUND";
export const PAREJAS_TORNEO = "PAREJAS_TORNEO";
export const PAREJAS_LOADING = "PAREJAS_LOADING";
export const SET_PAREJA_CONTRINCANTE = "SET_PAREJA_CONTRINCANTE";
