export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const USER_LOADING = "USER_LOADING";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const IS_ADMIN = "IS_ADMIN";
export const IS_NOT_ADMIN = "IS_NOT_ADMIN";

export const GET_CURRENT_TOURNAMENTS = "GET_CURRENT_TOURNAMENTS";
export const TOURNAMENTS_LOADING = "TOURNAMENTS_LOADING";

export const TOURNAMENTS_ADMIN_LOADING = "TOURNAMENTS_ADMIN_LOADING";
export const GET_CURRENT_ADMIN_TOURNAMENTS = "GET_CURRENT_ADMIN_TOURNAMENTS";

export const SET_SELECTED_TOURNAMENT = "SET_SELECTED_TOURNAMENT";

export const SET_SELECTED_TOURNAMENT_INFO = "SET_SELECTED_TOURNAMENT_INFO";

export const GET_USER1 = "GET_USER1";
export const GET_USER2 = "GET_USER2";

export const GET_MI_RONDA_INFO = "GET_MI_RONDA_INFO";
